version: '3.8'

services:
  processor:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.local
    ports:
      - '42069:42069'
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=db_username
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=db_name
    ports:
      - '5432:5432'
    volumes:
      - postgres_ponder_volume:/var/lib/postgres_ponder/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -q -U db_username -d db_name']

volumes:
  postgres_ponder_volume: